"""Extended security-master catalogue for the institutional router.

Rows stay presentation-agnostic so the catalogue can grow without coupling
market coverage to Streamlit.  Symbols follow the identifiers expected by the
terminal's current market-data adapters; provider availability is validated at
request time by those adapters.
"""

from __future__ import annotations

from typing import Iterable


AssetRow = tuple[str, str, str, str, str, tuple[str, ...]]


def _tags(value: str) -> tuple[str, ...]:
    return tuple(tag.strip() for tag in value.split("|") if tag.strip())


def _group(
    universe: str,
    engine: str,
    region: str,
    entries: Iterable[tuple[str, str, str]],
) -> tuple[AssetRow, ...]:
    return tuple(
        (symbol, name, universe, engine, region, _tags(tags))
        for symbol, name, tags in entries
    )


def _regional(
    universe: str,
    engine: str,
    entries: Iterable[tuple[str, str, str, str]],
) -> tuple[AssetRow, ...]:
    return tuple(
        (symbol, name, universe, engine, region, _tags(tags))
        for symbol, name, region, tags in entries
    )


EXPANDED_INSTRUMENT_ROWS: tuple[AssetRow, ...] = (
    # United States equities — technology, communication and platforms.
    *_group(
        "Equities",
        "Equity",
        "United States",
        (
            ("AMD", "Advanced Micro Devices", "semiconductors|AI|large cap"),
            ("AVGO", "Broadcom", "semiconductors|infrastructure|large cap"),
            ("ORCL", "Oracle", "software|cloud|large cap"),
            ("CRM", "Salesforce", "software|cloud|large cap"),
            ("ADBE", "Adobe", "software|digital media|large cap"),
            ("NFLX", "Netflix", "media|streaming|growth"),
            ("PLTR", "Palantir Technologies", "software|AI|data"),
            ("INTC", "Intel", "semiconductors|hardware"),
            ("QCOM", "Qualcomm", "semiconductors|wireless"),
            ("TXN", "Texas Instruments", "semiconductors|analog"),
            ("MU", "Micron Technology", "semiconductors|memory"),
            ("AMAT", "Applied Materials", "semiconductor equipment"),
            ("LRCX", "Lam Research", "semiconductor equipment"),
            ("KLAC", "KLA", "semiconductor equipment"),
            ("IBM", "IBM", "technology|consulting|AI"),
            ("NOW", "ServiceNow", "software|workflow|cloud"),
            ("PANW", "Palo Alto Networks", "cybersecurity|software"),
            ("CRWD", "CrowdStrike", "cybersecurity|software"),
            ("SNOW", "Snowflake", "cloud|data|software"),
            ("UBER", "Uber Technologies", "mobility|platform"),
            ("ABNB", "Airbnb", "travel|platform"),
            ("BKNG", "Booking Holdings", "travel|platform"),
            ("DIS", "Walt Disney", "media|entertainment"),
            ("T", "AT&T", "telecommunications|dividend"),
            ("VZ", "Verizon Communications", "telecommunications|dividend"),
            ("TMUS", "T-Mobile US", "telecommunications|growth"),
        ),
    ),
    # United States equities — consumer, industrial, energy and utilities.
    *_group(
        "Equities",
        "Equity",
        "United States",
        (
            ("NKE", "Nike", "consumer discretionary|apparel"),
            ("MCD", "McDonald's", "consumer discretionary|restaurants"),
            ("SBUX", "Starbucks", "consumer discretionary|restaurants"),
            ("HD", "Home Depot", "consumer discretionary|retail"),
            ("LOW", "Lowe's", "consumer discretionary|retail"),
            ("KO", "Coca-Cola", "consumer staples|beverages"),
            ("PEP", "PepsiCo", "consumer staples|beverages"),
            ("PG", "Procter & Gamble", "consumer staples|household"),
            ("PM", "Philip Morris International", "consumer staples|tobacco"),
            ("MO", "Altria", "consumer staples|tobacco"),
            ("GE", "GE Aerospace", "industrials|aerospace"),
            ("RTX", "RTX", "industrials|aerospace|defense"),
            ("LMT", "Lockheed Martin", "industrials|defense"),
            ("NOC", "Northrop Grumman", "industrials|defense"),
            ("DE", "Deere", "industrials|agriculture"),
            ("HON", "Honeywell", "industrials|automation"),
            ("UNP", "Union Pacific", "industrials|railroads"),
            ("UPS", "UPS", "industrials|logistics"),
            ("FDX", "FedEx", "industrials|logistics"),
            ("COP", "ConocoPhillips", "energy|exploration"),
            ("SLB", "SLB", "energy|services"),
            ("EOG", "EOG Resources", "energy|exploration"),
            ("OXY", "Occidental Petroleum", "energy|exploration"),
            ("NEE", "NextEra Energy", "utilities|renewables"),
            ("DUK", "Duke Energy", "utilities|electric"),
            ("SO", "Southern Company", "utilities|electric"),
        ),
    ),
    # United States equities — healthcare and financials.
    *_group(
        "Equities",
        "Equity",
        "United States",
        (
            ("JNJ", "Johnson & Johnson", "healthcare|pharmaceuticals"),
            ("PFE", "Pfizer", "healthcare|pharmaceuticals"),
            ("MRK", "Merck", "healthcare|pharmaceuticals"),
            ("ABBV", "AbbVie", "healthcare|biotechnology"),
            ("TMO", "Thermo Fisher Scientific", "healthcare|life sciences"),
            ("ISRG", "Intuitive Surgical", "healthcare|medical devices"),
            ("GILD", "Gilead Sciences", "healthcare|biotechnology"),
            ("AMGN", "Amgen", "healthcare|biotechnology"),
            ("MDT", "Medtronic", "healthcare|medical devices"),
            ("ELV", "Elevance Health", "healthcare|managed care"),
            ("V", "Visa", "financials|payments"),
            ("MA", "Mastercard", "financials|payments"),
            ("AXP", "American Express", "financials|payments"),
            ("MS", "Morgan Stanley", "financials|capital markets"),
            ("C", "Citigroup", "financials|banks"),
            ("BLK", "BlackRock", "financials|asset management"),
            ("SCHW", "Charles Schwab", "financials|brokerage"),
            ("SPGI", "S&P Global", "financials|data"),
            ("CME", "CME Group", "financials|exchange"),
            ("ICE", "Intercontinental Exchange", "financials|exchange"),
            ("CB", "Chubb", "financials|insurance"),
            ("BRK-B", "Berkshire Hathaway", "financials|conglomerate"),
        ),
    ),
    # Europe equities.
    *_regional(
        "Equities",
        "Equity",
        (
            ("SIE.DE", "Siemens", "Germany", "industrials|automation|Europe"),
            ("ALV.DE", "Allianz", "Germany", "insurance|financials|Europe"),
            ("DTE.DE", "Deutsche Telekom", "Germany", "telecommunications|Europe"),
            ("BMW.DE", "BMW", "Germany", "automotive|Europe"),
            ("MBG.DE", "Mercedes-Benz Group", "Germany", "automotive|Europe"),
            ("BAS.DE", "BASF", "Germany", "chemicals|Europe"),
            ("BAYN.DE", "Bayer", "Germany", "healthcare|chemicals|Europe"),
            ("IFX.DE", "Infineon Technologies", "Germany", "semiconductors|Europe"),
            ("ADS.DE", "Adidas", "Germany", "consumer|apparel|Europe"),
            ("SU.PA", "Schneider Electric", "France", "industrials|electrification|Europe"),
            ("SAN.PA", "Sanofi", "France", "healthcare|pharmaceuticals|Europe"),
            ("TTE.PA", "TotalEnergies", "France", "energy|Europe"),
            ("BN.PA", "Danone", "France", "consumer staples|Europe"),
            ("DG.PA", "Vinci", "France", "infrastructure|Europe"),
            ("SAF.PA", "Safran", "France", "aerospace|Europe"),
            ("RMS.PA", "Hermes International", "France", "luxury|Europe"),
            ("CS.PA", "AXA", "France", "insurance|Europe"),
            ("BNP.PA", "BNP Paribas", "France", "banks|Europe"),
            ("ACA.PA", "Credit Agricole", "France", "banks|Europe"),
            ("AZN.L", "AstraZeneca", "United Kingdom", "healthcare|pharmaceuticals|Europe"),
            ("HSBA.L", "HSBC", "United Kingdom", "banks|Europe"),
            ("BP.L", "BP", "United Kingdom", "energy|Europe"),
            ("ULVR.L", "Unilever", "United Kingdom", "consumer staples|Europe"),
            ("GSK.L", "GSK", "United Kingdom", "healthcare|pharmaceuticals|Europe"),
            ("RIO.L", "Rio Tinto", "United Kingdom", "materials|mining|Europe"),
            ("BARC.L", "Barclays", "United Kingdom", "banks|Europe"),
            ("NOVN.SW", "Novartis", "Switzerland", "healthcare|pharmaceuticals|Europe"),
            ("ROG.SW", "Roche", "Switzerland", "healthcare|pharmaceuticals|Europe"),
            ("UBS", "UBS Group", "Switzerland", "banks|wealth management|Europe"),
            ("ZURN.SW", "Zurich Insurance", "Switzerland", "insurance|Europe"),
            ("ADYEN.AS", "Adyen", "Netherlands", "payments|technology|Europe"),
            ("ASM.AS", "ASM International", "Netherlands", "semiconductors|Europe"),
            ("ENEL.MI", "Enel", "Italy", "utilities|Europe"),
            ("ISP.MI", "Intesa Sanpaolo", "Italy", "banks|Europe"),
            ("ENI.MI", "Eni", "Italy", "energy|Europe"),
            ("UCG.MI", "UniCredit", "Italy", "banks|Europe"),
            ("IBE.MC", "Iberdrola", "Spain", "utilities|renewables|Europe"),
            ("SAN.MC", "Banco Santander", "Spain", "banks|Europe"),
            ("ITX.MC", "Inditex", "Spain", "consumer|retail|Europe"),
            ("EQNR.OL", "Equinor", "Norway", "energy|Europe"),
            ("VOLV-B.ST", "Volvo", "Sweden", "industrials|automotive|Europe"),
            ("ERIC-B.ST", "Ericsson", "Sweden", "telecommunications|Europe"),
        ),
    ),
    # Asia-Pacific and emerging-market equities.
    *_regional(
        "Equities",
        "Equity",
        (
            ("SONY", "Sony Group ADR", "Japan", "technology|consumer|Asia"),
            ("HMC", "Honda Motor ADR", "Japan", "automotive|Asia"),
            ("MUFG", "Mitsubishi UFJ Financial ADR", "Japan", "banks|Asia"),
            ("SMFG", "Sumitomo Mitsui Financial ADR", "Japan", "banks|Asia"),
            ("6758.T", "Sony Group", "Japan", "technology|consumer|Asia"),
            ("8306.T", "Mitsubishi UFJ Financial", "Japan", "banks|Asia"),
            ("6861.T", "Keyence", "Japan", "automation|technology|Asia"),
            ("9432.T", "Nippon Telegraph & Telephone", "Japan", "telecommunications|Asia"),
            ("8035.T", "Tokyo Electron", "Japan", "semiconductor equipment|Asia"),
            ("8058.T", "Mitsubishi Corporation", "Japan", "conglomerate|Asia"),
            ("000660.KS", "SK Hynix", "South Korea", "semiconductors|memory|Asia"),
            ("035420.KS", "NAVER", "South Korea", "internet|technology|Asia"),
            ("1299.HK", "AIA Group", "Hong Kong", "insurance|Asia"),
            ("3690.HK", "Meituan", "China", "consumer|platform|Asia"),
            ("9988.HK", "Alibaba Group", "China", "consumer|cloud|Asia"),
            ("9618.HK", "JD.com", "China", "consumer|e-commerce|Asia"),
            ("2318.HK", "Ping An Insurance", "China", "insurance|Asia"),
            ("1398.HK", "ICBC", "China", "banks|Asia"),
            ("1211.HK", "BYD", "China", "automotive|electric vehicles|Asia"),
            ("INFY", "Infosys ADR", "India", "technology|services|Asia"),
            ("HDB", "HDFC Bank ADR", "India", "banks|Asia"),
            ("IBN", "ICICI Bank ADR", "India", "banks|Asia"),
            ("RELIANCE.NS", "Reliance Industries", "India", "energy|consumer|Asia"),
            ("TCS.NS", "Tata Consultancy Services", "India", "technology|services|Asia"),
            ("SE", "Sea Limited", "Singapore", "internet|consumer|Asia"),
            ("CBA.AX", "Commonwealth Bank", "Australia", "banks|Asia Pacific"),
            ("BHP.AX", "BHP Group", "Australia", "materials|mining|Asia Pacific"),
            ("CSL.AX", "CSL", "Australia", "healthcare|biotechnology|Asia Pacific"),
            ("WES.AX", "Wesfarmers", "Australia", "consumer|conglomerate|Asia Pacific"),
            ("FMG.AX", "Fortescue", "Australia", "materials|mining|Asia Pacific"),
        ),
    ),
    # Canada and Latin America equities.
    *_regional(
        "Equities",
        "Equity",
        (
            ("RY", "Royal Bank of Canada", "Canada", "banks|Americas"),
            ("TD", "Toronto-Dominion Bank", "Canada", "banks|Americas"),
            ("SHOP", "Shopify", "Canada", "technology|commerce|Americas"),
            ("CNQ", "Canadian Natural Resources", "Canada", "energy|Americas"),
            ("ENB", "Enbridge", "Canada", "energy|pipelines|Americas"),
            ("BCE", "BCE", "Canada", "telecommunications|Americas"),
            ("NU", "Nu Holdings", "Brazil", "financial technology|Americas"),
            ("PBR", "Petrobras ADR", "Brazil", "energy|Americas"),
            ("VALE", "Vale ADR", "Brazil", "materials|mining|Americas"),
            ("ITUB", "Itau Unibanco ADR", "Brazil", "banks|Americas"),
            ("MELI", "MercadoLibre", "Latin America", "consumer|payments|Americas"),
            ("AMX", "America Movil ADR", "Mexico", "telecommunications|Americas"),
        ),
    ),
    # Additional global equity indices.
    *_regional(
        "Indices",
        "Equity",
        (
            ("^IXIC", "Nasdaq Composite", "United States", "broad market|technology"),
            ("^NYA", "NYSE Composite", "United States", "broad market"),
            ("^MID", "S&P MidCap 400", "United States", "mid cap"),
            ("^OEX", "S&P 100", "United States", "large cap"),
            ("^SPTSX", "S&P/TSX Composite", "Canada", "broad market|Americas"),
            ("^BVSP", "Bovespa", "Brazil", "broad market|Americas"),
            ("^MXX", "S&P/BMV IPC", "Mexico", "broad market|Americas"),
            ("^MERV", "MERVAL", "Argentina", "broad market|Americas"),
            ("^IBEX", "IBEX 35", "Spain", "large cap|Europe"),
            ("^AEX", "AEX", "Netherlands", "large cap|Europe"),
            ("^SSMI", "SMI", "Switzerland", "large cap|Europe"),
            ("FTSEMIB.MI", "FTSE MIB", "Italy", "large cap|Europe"),
            ("^ATX", "ATX", "Austria", "large cap|Europe"),
            ("^BFX", "BEL 20", "Belgium", "large cap|Europe"),
            ("^KS11", "KOSPI", "South Korea", "broad market|Asia"),
            ("000001.SS", "Shanghai Composite", "China", "broad market|Asia"),
            ("399001.SZ", "Shenzhen Component", "China", "broad market|Asia"),
            ("^TWII", "Taiwan Weighted", "Taiwan", "broad market|Asia"),
            ("^STI", "Straits Times", "Singapore", "broad market|Asia"),
            ("^JKSE", "Jakarta Composite", "Indonesia", "broad market|Asia"),
            ("^BSESN", "BSE Sensex", "India", "large cap|Asia"),
            ("^NSEI", "Nifty 50", "India", "large cap|Asia"),
            ("^NZ50", "S&P/NZX 50", "New Zealand", "broad market|Asia Pacific"),
            ("^TA125.TA", "TA-125", "Israel", "broad market|Middle East"),
        ),
    ),
    # Broad, factor, country and thematic ETFs.
    *_group(
        "ETFs",
        "Equity",
        "United States",
        (
            ("VOO", "Vanguard S&P 500 ETF", "broad market|large cap"),
            ("IVV", "iShares Core S&P 500 ETF", "broad market|large cap"),
            ("VTI", "Vanguard Total Stock Market ETF", "broad market"),
            ("SCHB", "Schwab US Broad Market ETF", "broad market"),
            ("RSP", "Invesco S&P 500 Equal Weight ETF", "equal weight|factor"),
            ("MDY", "SPDR S&P MidCap 400 ETF", "mid cap"),
            ("IJH", "iShares Core S&P Mid-Cap ETF", "mid cap"),
            ("VB", "Vanguard Small-Cap ETF", "small cap"),
            ("VBR", "Vanguard Small-Cap Value ETF", "small cap|value"),
            ("VTV", "Vanguard Value ETF", "large cap|value"),
            ("VUG", "Vanguard Growth ETF", "large cap|growth"),
            ("QUAL", "iShares MSCI USA Quality Factor ETF", "quality|factor"),
            ("MTUM", "iShares MSCI USA Momentum Factor ETF", "momentum|factor"),
            ("USMV", "iShares MSCI USA Min Vol Factor ETF", "low volatility|factor"),
            ("SPLV", "Invesco S&P 500 Low Volatility ETF", "low volatility|factor"),
            ("IWF", "iShares Russell 1000 Growth ETF", "growth|factor"),
            ("IWD", "iShares Russell 1000 Value ETF", "value|factor"),
            ("VIG", "Vanguard Dividend Appreciation ETF", "dividend|quality"),
            ("VYM", "Vanguard High Dividend Yield ETF", "dividend|income"),
            ("SCHD", "Schwab US Dividend Equity ETF", "dividend|quality"),
            ("DGRO", "iShares Core Dividend Growth ETF", "dividend|growth"),
            ("XLY", "Consumer Discretionary Select Sector SPDR", "sector|consumer discretionary"),
            ("XLP", "Consumer Staples Select Sector SPDR", "sector|consumer staples"),
            ("XLU", "Utilities Select Sector SPDR", "sector|utilities"),
            ("XLRE", "Real Estate Select Sector SPDR", "sector|real estate"),
            ("XLC", "Communication Services Select Sector SPDR", "sector|communication"),
            ("SMH", "VanEck Semiconductor ETF", "semiconductors|thematic"),
            ("SOXX", "iShares Semiconductor ETF", "semiconductors|thematic"),
            ("IGV", "iShares Expanded Tech-Software Sector ETF", "software|thematic"),
            ("XBI", "SPDR S&P Biotech ETF", "biotechnology|thematic"),
            ("KRE", "SPDR S&P Regional Banking ETF", "banks|sector"),
            ("ITA", "iShares US Aerospace & Defense ETF", "aerospace|defense"),
            ("ICLN", "iShares Global Clean Energy ETF", "clean energy|thematic"),
            ("TAN", "Invesco Solar ETF", "solar|thematic"),
            ("ARKK", "ARK Innovation ETF", "innovation|growth"),
            ("TQQQ", "ProShares UltraPro QQQ", "leveraged|growth"),
            ("SQQQ", "ProShares UltraPro Short QQQ", "inverse|hedging"),
            ("SPXL", "Direxion Daily S&P 500 Bull 3X", "leveraged|large cap"),
            ("SPXS", "Direxion Daily S&P 500 Bear 3X", "inverse|hedging"),
        ),
    ),
    *_regional(
        "ETFs",
        "Equity",
        (
            ("IEFA", "iShares Core MSCI EAFE ETF", "Developed Markets", "international|developed"),
            ("ACWI", "iShares MSCI ACWI ETF", "Global", "international|all country"),
            ("VT", "Vanguard Total World Stock ETF", "Global", "international|all country"),
            ("VXUS", "Vanguard Total International Stock ETF", "Global ex-US", "international"),
            ("EWJ", "iShares MSCI Japan ETF", "Japan", "country|Asia"),
            ("EWZ", "iShares MSCI Brazil ETF", "Brazil", "country|Americas"),
            ("EWC", "iShares MSCI Canada ETF", "Canada", "country|Americas"),
            ("EWW", "iShares MSCI Mexico ETF", "Mexico", "country|Americas"),
            ("EWU", "iShares MSCI United Kingdom ETF", "United Kingdom", "country|Europe"),
            ("EWQ", "iShares MSCI France ETF", "France", "country|Europe"),
            ("EWG", "iShares MSCI Germany ETF", "Germany", "country|Europe"),
            ("EWI", "iShares MSCI Italy ETF", "Italy", "country|Europe"),
            ("EWP", "iShares MSCI Spain ETF", "Spain", "country|Europe"),
            ("EWL", "iShares MSCI Switzerland ETF", "Switzerland", "country|Europe"),
            ("EWA", "iShares MSCI Australia ETF", "Australia", "country|Asia Pacific"),
            ("EWT", "iShares MSCI Taiwan ETF", "Taiwan", "country|Asia"),
            ("EWY", "iShares MSCI South Korea ETF", "South Korea", "country|Asia"),
            ("MCHI", "iShares MSCI China ETF", "China", "country|Asia"),
            ("INDA", "iShares MSCI India ETF", "India", "country|Asia"),
            ("FM", "iShares MSCI Frontier and Select EM ETF", "Frontier Markets", "frontier|international"),
            ("KSA", "iShares MSCI Saudi Arabia ETF", "Saudi Arabia", "country|Middle East"),
            ("TUR", "iShares MSCI Turkey ETF", "Turkey", "country|emerging markets"),
            ("EZA", "iShares MSCI South Africa ETF", "South Africa", "country|emerging markets"),
            ("ARGT", "Global X MSCI Argentina ETF", "Argentina", "country|Americas"),
        ),
    ),
    *_group(
        "ETFs",
        "Equity",
        "Global",
        (
            ("GLD", "SPDR Gold Shares", "gold|precious metals"),
            ("SLV", "iShares Silver Trust", "silver|precious metals"),
            ("USO", "United States Oil Fund", "oil|energy"),
            ("UNG", "United States Natural Gas Fund", "natural gas|energy"),
            ("DBA", "Invesco DB Agriculture Fund", "agriculture|commodities"),
            ("DBC", "Invesco DB Commodity Index Tracking Fund", "broad commodities"),
            ("KMLM", "KFA Mount Lucas Managed Futures Index Strategy ETF", "managed futures|alternatives"),
            ("CTA", "Simplify Managed Futures Strategy ETF", "managed futures|alternatives"),
            ("REM", "iShares Mortgage Real Estate ETF", "real estate|income"),
            ("PFF", "iShares Preferred and Income Securities ETF", "preferreds|income"),
            ("UUP", "Invesco DB US Dollar Index Bullish Fund", "currency|US dollar"),
            ("FXE", "Invesco CurrencyShares Euro Trust", "currency|euro"),
            ("FXY", "Invesco CurrencyShares Japanese Yen Trust", "currency|yen"),
        ),
    ),
    # G10 crosses and emerging-market FX.
    *_regional(
        "FX",
        "FX",
        (
            ("AUDJPY=X", "Australian Dollar / Japanese Yen", "G10", "cross|carry"),
            ("CADJPY=X", "Canadian Dollar / Japanese Yen", "G10", "cross|carry"),
            ("CHFJPY=X", "Swiss Franc / Japanese Yen", "G10", "cross"),
            ("NZDJPY=X", "New Zealand Dollar / Japanese Yen", "G10", "cross|carry"),
            ("GBPCAD=X", "British Pound / Canadian Dollar", "G10", "cross"),
            ("GBPAUD=X", "British Pound / Australian Dollar", "G10", "cross"),
            ("GBPNZD=X", "British Pound / New Zealand Dollar", "G10", "cross"),
            ("EURAUD=X", "Euro / Australian Dollar", "G10", "cross"),
            ("EURCAD=X", "Euro / Canadian Dollar", "G10", "cross"),
            ("EURNZD=X", "Euro / New Zealand Dollar", "G10", "cross"),
            ("AUDCAD=X", "Australian Dollar / Canadian Dollar", "G10", "cross"),
            ("AUDNZD=X", "Australian Dollar / New Zealand Dollar", "G10", "cross"),
            ("CADCHF=X", "Canadian Dollar / Swiss Franc", "G10", "cross"),
            ("NZDCAD=X", "New Zealand Dollar / Canadian Dollar", "G10", "cross"),
            ("NOKSEK=X", "Norwegian Krone / Swedish Krona", "G10", "cross|Scandinavia"),
            ("USDINR=X", "US Dollar / Indian Rupee", "Emerging Markets", "Asia|EM FX"),
            ("USDBRL=X", "US Dollar / Brazilian Real", "Emerging Markets", "Americas|EM FX"),
            ("USDCNH=X", "US Dollar / Offshore Renminbi", "Emerging Markets", "China|EM FX"),
            ("USDKRW=X", "US Dollar / South Korean Won", "Emerging Markets", "Asia|EM FX"),
            ("USDSGD=X", "US Dollar / Singapore Dollar", "Asia", "Asia FX"),
            ("USDHKD=X", "US Dollar / Hong Kong Dollar", "Asia", "peg|Asia FX"),
            ("USDPLN=X", "US Dollar / Polish Zloty", "Emerging Markets", "Europe|EM FX"),
            ("USDHUF=X", "US Dollar / Hungarian Forint", "Emerging Markets", "Europe|EM FX"),
            ("USDCZK=X", "US Dollar / Czech Koruna", "Emerging Markets", "Europe|EM FX"),
            ("USDCOP=X", "US Dollar / Colombian Peso", "Emerging Markets", "Americas|EM FX"),
            ("USDCLP=X", "US Dollar / Chilean Peso", "Emerging Markets", "Americas|EM FX"),
            ("USDIDR=X", "US Dollar / Indonesian Rupiah", "Emerging Markets", "Asia|EM FX"),
            ("USDPHP=X", "US Dollar / Philippine Peso", "Emerging Markets", "Asia|EM FX"),
            ("USDTHB=X", "US Dollar / Thai Baht", "Emerging Markets", "Asia|EM FX"),
            ("EURPLN=X", "Euro / Polish Zloty", "Emerging Markets", "Europe|EM FX"),
        ),
    ),
    # Global sovereign and money-market instruments represented by liquid ETFs/futures.
    *_regional(
        "Rates",
        "Rates",
        (
            ("SR3=F", "Three-Month SOFR Future", "United States", "money market|future"),
            ("ZQ=F", "30-Day Federal Funds Future", "United States", "money market|future"),
            ("VGSH", "Vanguard Short-Term Treasury ETF", "United States", "sovereign|short duration"),
            ("VGIT", "Vanguard Intermediate-Term Treasury ETF", "United States", "sovereign|duration"),
            ("VGLT", "Vanguard Long-Term Treasury ETF", "United States", "sovereign|long duration"),
            ("EDV", "Vanguard Extended Duration Treasury ETF", "United States", "sovereign|long duration"),
            ("GOVZ", "iShares 25+ Year Treasury STRIPS Bond ETF", "United States", "sovereign|zero coupon"),
            ("TLH", "iShares 10-20 Year Treasury Bond ETF", "United States", "sovereign|duration"),
            ("SPTL", "SPDR Portfolio Long Term Treasury ETF", "United States", "sovereign|long duration"),
            ("IUSB", "iShares Core Total USD Bond Market ETF", "United States", "aggregate|fixed income"),
            ("BND", "Vanguard Total Bond Market ETF", "United States", "aggregate|fixed income"),
            ("AGG", "iShares Core US Aggregate Bond ETF", "United States", "aggregate|fixed income"),
            ("MBB", "iShares MBS ETF", "United States", "mortgage-backed securities"),
            ("VMBS", "Vanguard Mortgage-Backed Securities ETF", "United States", "mortgage-backed securities"),
            ("USFR", "WisdomTree Floating Rate Treasury Fund", "United States", "floating rate|Treasury"),
            ("TFLO", "iShares Treasury Floating Rate Bond ETF", "United States", "floating rate|Treasury"),
            ("VTEB", "Vanguard Tax-Exempt Bond ETF", "United States", "municipal|tax exempt"),
            ("MUB", "iShares National Muni Bond ETF", "United States", "municipal|tax exempt"),
            ("VTIP", "Vanguard Short-Term Inflation-Protected Securities ETF", "United States", "inflation-linked|short duration"),
            ("BNDX", "Vanguard Total International Bond ETF", "Global ex-US", "aggregate|international"),
            ("BWX", "SPDR Bloomberg International Treasury Bond ETF", "Global ex-US", "sovereign|international"),
            ("IGOV", "iShares International Treasury Bond ETF", "Global ex-US", "sovereign|international"),
            ("EMLC", "VanEck Emerging Markets Local Currency Bond ETF", "Emerging Markets", "sovereign|local currency"),
            ("HYD", "VanEck High Yield Muni ETF", "United States", "municipal|high yield"),
        ),
    ),
    # Investment-grade, high-yield, loans, convertibles and structured credit.
    *_regional(
        "Credit",
        "Rates",
        (
            ("IGIB", "iShares 5-10 Year Investment Grade Corporate Bond ETF", "United States", "IG|spread|intermediate"),
            ("IGSB", "iShares 1-5 Year Investment Grade Corporate Bond ETF", "United States", "IG|spread|short duration"),
            ("SLQD", "iShares 0-5 Year Investment Grade Corporate Bond ETF", "United States", "IG|spread|short duration"),
            ("SPSB", "SPDR Portfolio Short Term Corporate Bond ETF", "United States", "IG|spread|short duration"),
            ("USIG", "iShares Broad USD Investment Grade Corporate Bond ETF", "United States", "IG|spread"),
            ("VCLT", "Vanguard Long-Term Corporate Bond ETF", "United States", "IG|spread|long duration"),
            ("SPIB", "SPDR Portfolio Intermediate Term Corporate Bond ETF", "United States", "IG|spread|intermediate"),
            ("SPLB", "SPDR Portfolio Long Term Corporate Bond ETF", "United States", "IG|spread|long duration"),
            ("HYLB", "Xtrackers USD High Yield Corporate Bond ETF", "United States", "HY|spread"),
            ("USHY", "iShares Broad USD High Yield Corporate Bond ETF", "United States", "HY|spread"),
            ("SJNK", "SPDR Bloomberg Short Term High Yield Bond ETF", "United States", "HY|spread|short duration"),
            ("SHYG", "iShares 0-5 Year High Yield Corporate Bond ETF", "United States", "HY|spread|short duration"),
            ("HYEM", "VanEck Emerging Markets High Yield Bond ETF", "Emerging Markets", "HY|sovereign|corporate"),
            ("CEMB", "iShares J.P. Morgan EM Corporate Bond ETF", "Emerging Markets", "corporate|EM credit"),
            ("SRLN", "SPDR Blackstone Senior Loan ETF", "United States", "loans|floating rate"),
            ("FTSL", "First Trust Senior Loan Fund", "United States", "loans|floating rate"),
            ("CLOA", "BlackRock AAA CLO ETF", "United States", "CLO|structured credit"),
            ("JAAA", "Janus Henderson AAA CLO ETF", "United States", "CLO|structured credit"),
            ("ICVT", "iShares Convertible Bond ETF", "United States", "convertible|hybrid"),
            ("CWB", "SPDR Bloomberg Convertible Securities ETF", "United States", "convertible|hybrid"),
            ("BINC", "BlackRock Flexible Income ETF", "Global", "multi-sector|income"),
            ("IAGG", "iShares Core International Aggregate Bond ETF", "Global ex-US", "aggregate|international"),
        ),
    ),
    # Additional commodity futures and liquid thematic proxies.
    *_group(
        "Commodities",
        "Commodities",
        "Global",
        (
            ("LE=F", "Live Cattle", "livestock|future"),
            ("HE=F", "Lean Hogs", "livestock|future"),
            ("GF=F", "Feeder Cattle", "livestock|future"),
            ("OJ=F", "Orange Juice", "softs|future"),
            ("LBS=F", "Lumber", "forest products|future"),
            ("ZR=F", "Rough Rice", "agriculture|future"),
            ("ZO=F", "Oats", "agriculture|future"),
            ("ZM=F", "Soybean Meal", "agriculture|future"),
            ("ZL=F", "Soybean Oil", "agriculture|future"),
            ("MGC=F", "Micro Gold", "precious metals|future"),
            ("SIL=F", "Micro Silver", "precious metals|future"),
            ("MCL=F", "Micro WTI Crude Oil", "energy|future"),
            ("QG=F", "E-mini Natural Gas", "energy|future"),
            ("URA", "Global X Uranium ETF", "uranium|nuclear fuel"),
            ("COPX", "Global X Copper Miners ETF", "copper|mining"),
            ("REMX", "VanEck Rare Earth and Strategic Metals ETF", "rare earths|mining"),
            ("LIT", "Global X Lithium & Battery Tech ETF", "lithium|battery materials"),
            ("WEAT", "Teucrium Wheat Fund", "wheat|agriculture"),
            ("CORN", "Teucrium Corn Fund", "corn|agriculture"),
            ("SOYB", "Teucrium Soybean Fund", "soybeans|agriculture"),
            ("CPER", "United States Copper Index Fund", "copper|industrial metals"),
        ),
    ),
    # Digital-asset majors, protocols and liquid thematic tokens.
    *_group(
        "Digital Assets",
        "Equity",
        "Global",
        (
            ("DOGE-USD", "Dogecoin", "crypto|payments"),
            ("DOT-USD", "Polkadot", "crypto|interoperability"),
            ("LTC-USD", "Litecoin", "crypto|payments"),
            ("BCH-USD", "Bitcoin Cash", "crypto|payments"),
            ("UNI-USD", "Uniswap", "crypto|DeFi|exchange"),
            ("AAVE-USD", "Aave", "crypto|DeFi|lending"),
            ("ATOM-USD", "Cosmos", "crypto|interoperability"),
            ("NEAR-USD", "NEAR Protocol", "crypto|smart contracts"),
            ("ICP-USD", "Internet Computer", "crypto|compute"),
            ("FIL-USD", "Filecoin", "crypto|storage"),
            ("ETC-USD", "Ethereum Classic", "crypto|smart contracts"),
            ("XLM-USD", "Stellar", "crypto|payments"),
            ("HBAR-USD", "Hedera", "crypto|enterprise"),
            ("ARB-USD", "Arbitrum", "crypto|layer 2"),
            ("OP-USD", "Optimism", "crypto|layer 2"),
            ("APT-USD", "Aptos", "crypto|smart contracts"),
            ("SUI-USD", "Sui", "crypto|smart contracts"),
            ("INJ-USD", "Injective", "crypto|DeFi"),
            ("RENDER-USD", "Render", "crypto|compute|AI"),
            ("STX-USD", "Stacks", "crypto|Bitcoin layer"),
            ("MKR-USD", "Maker", "crypto|DeFi|stablecoin"),
            ("LDO-USD", "Lido DAO", "crypto|staking"),
            ("TRX-USD", "TRON", "crypto|payments"),
            ("SHIB-USD", "Shiba Inu", "crypto|meme"),
            ("PEPE-USD", "Pepe", "crypto|meme"),
            ("ALGO-USD", "Algorand", "crypto|smart contracts"),
        ),
    ),
    # Volatility, skew and cross-asset implied-risk gauges.
    *_group(
        "Volatility",
        "Equity",
        "United States",
        (
            ("^VVIX", "Cboe VIX of VIX Index", "volatility of volatility|implied volatility"),
            ("^SKEW", "Cboe SKEW Index", "tail risk|options"),
            ("^GVZ", "Cboe Gold ETF Volatility Index", "gold|implied volatility"),
            ("^OVX", "Cboe Crude Oil ETF Volatility Index", "oil|implied volatility"),
            ("VX=F", "VIX Future", "volatility|future"),
            ("SVOL", "Simplify Volatility Premium ETF", "volatility premium|income"),
            ("VIXY", "ProShares VIX Short-Term Futures ETF", "volatility|short term"),
            ("VIXM", "ProShares VIX Mid-Term Futures ETF", "volatility|mid term"),
            ("ZIVB", "Volatility Shares -1x Short VIX Mid-Term Futures Strategy ETF", "short volatility|mid term"),
            ("UVIX", "2x Long VIX Futures ETF", "leveraged volatility|short term"),
        ),
    ),
)
