from __future__ import annotations

import pandas as pd


# The registry is a taxonomy, not a claim that every force is observable in the current run.
# It is intentionally broader than the default data feeds so the section can absorb future
# macro, geopolitical, flow, derivatives, climate or alternative-data inputs without a rewrite.
_REGISTRY_ROWS = [
    # Fundamental / systematic
    ("Broad equity market", "Fundamental/Systematic", "Market beta", "Continuous", "SPY", "proxy"),
    ("Growth / technology style", "Fundamental/Systematic", "Style", "Continuous", "QQQ", "proxy"),
    ("Small-cap / size", "Fundamental/Systematic", "Style", "Continuous", "IWM", "proxy"),
    ("Semiconductor industry", "Fundamental/Systematic", "Industry", "Continuous", "SMH", "proxy"),
    ("Semiconductor industry alt", "Fundamental/Systematic", "Industry", "Continuous", "SOXX", "proxy"),
    ("Value factor", "Fundamental/Systematic", "Style", "Continuous", None, "injected"),
    ("Momentum factor", "Fundamental/Systematic", "Style", "Continuous", None, "injected"),
    ("Quality factor", "Fundamental/Systematic", "Style", "Continuous", None, "injected"),
    ("Low-volatility factor", "Fundamental/Systematic", "Style", "Continuous", None, "injected"),
    ("Country / regional equity", "Fundamental/Systematic", "Geography", "Continuous", None, "injected"),
    ("Cash-flow news", "Fundamental/Systematic", "Fundamentals", "Event/Continuous", None, "injected"),
    ("Discount-rate news", "Fundamental/Systematic", "Fundamentals", "Event/Continuous", None, "injected"),
    ("Earnings surprise", "Fundamental/Systematic", "Fundamentals", "Event", None, "event"),
    ("Guidance surprise", "Fundamental/Systematic", "Fundamentals", "Event", None, "event"),
    ("Analyst revisions", "Fundamental/Systematic", "Fundamentals", "Continuous/Event", None, "injected"),
    ("Valuation / duration equity", "Fundamental/Systematic", "Fundamentals", "Continuous", None, "injected"),
    ("Balance-sheet leverage", "Fundamental/Systematic", "Fundamentals", "Slow-moving", None, "metadata"),
    ("Supply-chain exposure", "Fundamental/Systematic", "Supply chain", "Slow/Event", None, "metadata"),
    ("Customer concentration", "Fundamental/Systematic", "Supply chain", "Slow/Event", None, "metadata"),

    # Exogenous macro / policy
    ("Long-duration rates", "Exogenous", "Rates", "Continuous", "TLT", "proxy"),
    ("Intermediate rates", "Exogenous", "Rates", "Continuous", "IEF", "proxy"),
    ("Real yields", "Exogenous", "Rates", "Continuous", None, "injected"),
    ("Yield-curve level", "Exogenous", "Rates", "Continuous", None, "injected"),
    ("Yield-curve slope", "Exogenous", "Rates", "Continuous", None, "injected"),
    ("Yield-curve curvature", "Exogenous", "Rates", "Continuous", None, "injected"),
    ("US 5Y rates", "Exogenous", "Rates", "Continuous", None, "injected"),
    ("US 30Y rates", "Exogenous", "Rates", "Continuous", None, "injected"),
    ("Yield-curve slope 10Y-3M", "Exogenous", "Rates", "Continuous", None, "injected"),
    ("Term premium", "Exogenous", "Rates", "Continuous", None, "injected"),
    ("Fed policy rate change", "Exogenous", "Monetary policy", "Continuous/Event", None, "injected"),
    ("ECB policy rate change", "Exogenous", "Monetary policy", "Continuous/Event", None, "injected"),
    ("Fed-ECB policy divergence", "Exogenous", "Monetary policy", "Continuous", None, "injected"),
    ("Fed policy surprise", "Exogenous", "Monetary policy", "Event", None, "event"),
    ("ECB policy surprise", "Exogenous", "Monetary policy", "Event", None, "event"),
    ("BoE policy surprise", "Exogenous", "Monetary policy", "Event", None, "event"),
    ("BoJ policy surprise", "Exogenous", "Monetary policy", "Event", None, "event"),
    ("PBoC policy surprise", "Exogenous", "Monetary policy", "Event", None, "event"),
    ("Relative monetary-policy surprise", "Exogenous", "Monetary policy", "Event", None, "event"),
    ("QE / QT / central-bank balance sheet", "Exogenous", "Monetary policy", "Continuous/Event", None, "injected"),
    ("Inflation surprise", "Exogenous", "Macro", "Event", None, "event"),
    ("Inflation expectations / breakevens", "Exogenous", "Macro", "Continuous", None, "injected"),
    ("5Y inflation expectations", "Exogenous", "Macro", "Continuous", None, "injected"),
    ("Financial conditions", "Exogenous", "Macro-financial", "Continuous", None, "injected"),
    ("Adjusted financial conditions", "Exogenous", "Macro-financial", "Continuous", None, "injected"),
    ("Financial stress", "Exogenous", "Macro-financial", "Continuous", None, "injected"),
    ("Growth surprise", "Exogenous", "Macro", "Event", None, "event"),
    ("PMI / ISM surprise", "Exogenous", "Macro", "Event", None, "event"),
    ("Payrolls / labor surprise", "Exogenous", "Macro", "Event", None, "event"),
    ("Fiscal impulse", "Exogenous", "Fiscal", "Continuous/Event", None, "injected"),
    ("Treasury cash balance / TGA", "Exogenous", "Fiscal", "Continuous", None, "injected"),
    ("Treasury / sovereign issuance", "Exogenous", "Fiscal", "Continuous/Event", None, "injected"),
    ("Tax change", "Exogenous", "Fiscal", "Event", None, "event"),
    ("Subsidy / tax-credit policy", "Exogenous", "Fiscal", "Event", None, "event"),
    ("USD factor", "Exogenous", "FX", "Continuous", "UUP", "proxy"),
    ("EUR/USD", "Exogenous", "FX", "Continuous", None, "injected"),
    ("USD/JPY", "Exogenous", "FX", "Continuous", None, "injected"),
    ("FX carry / basis", "Exogenous", "FX", "Continuous", None, "injected"),
    ("High-yield credit", "Exogenous", "Credit", "Continuous", "HYG", "proxy"),
    ("Investment-grade credit", "Exogenous", "Credit", "Continuous", "LQD", "proxy"),
    ("CDS / credit-spread shock", "Exogenous", "Credit", "Continuous", None, "injected"),
    ("Sovereign-risk spread", "Exogenous", "Credit", "Continuous", None, "injected"),
    ("Oil / energy", "Exogenous", "Commodities", "Continuous", "USO", "proxy"),
    ("Gold / safe haven", "Exogenous", "Commodities", "Continuous", "GLD", "proxy"),
    ("Copper / industrial metals", "Exogenous", "Commodities", "Continuous", None, "injected"),
    ("Natural gas / power", "Exogenous", "Commodities", "Continuous", None, "injected"),
    ("Agricultural inputs", "Exogenous", "Commodities", "Continuous", None, "injected"),
    ("Inventory / commodity curve", "Exogenous", "Commodities", "Continuous", None, "injected"),
    ("Implied volatility / risk aversion", "Exogenous", "Volatility", "Continuous", "^VIX", "proxy"),
    ("Rates volatility / MOVE", "Exogenous", "Volatility", "Continuous", None, "injected"),
    ("Variance risk premium", "Exogenous", "Volatility", "Continuous", None, "injected"),
    ("Geopolitical-risk index", "Exogenous", "Geopolitics", "Continuous/Event", None, "injected"),
    ("Geopolitical threats index", "Exogenous", "Geopolitics", "Continuous", None, "injected"),
    ("Geopolitical acts index", "Exogenous", "Geopolitics", "Continuous", None, "injected"),
    ("Geopolitical oil-disruption risk", "Exogenous", "Geopolitics/Energy", "Continuous", None, "injected"),
    ("War / conflict escalation", "Exogenous", "Geopolitics", "Event", None, "event"),
    ("Sanctions", "Exogenous", "Geopolitics", "Event", None, "event"),
    ("Export controls", "Exogenous", "Geopolitics", "Event", None, "event"),
    ("Tariffs / trade policy", "Exogenous", "Trade policy", "Event", None, "event"),
    ("Regulation / antitrust", "Exogenous", "Regulation", "Event", None, "event"),
    ("Election / political regime", "Exogenous", "Politics", "Event/Regime", None, "event"),
    ("Climate / physical-risk shock", "Exogenous", "Climate", "Event/Continuous", None, "injected"),
    ("Weather / catastrophe", "Exogenous", "Climate", "Event", None, "event"),

    # Endogenous market forces
    ("Market liquidity", "Endogenous Market", "Liquidity", "Continuous", None, "injected"),
    ("Bid-ask spread", "Endogenous Market", "Liquidity", "Continuous", None, "liquidity"),
    ("Market depth", "Endogenous Market", "Liquidity", "Continuous", None, "liquidity"),
    ("ADV / turnover", "Endogenous Market", "Liquidity", "Continuous", None, "liquidity"),
    ("Funding / repo conditions", "Endogenous Market", "Funding", "Continuous", None, "injected"),
    ("Repo / funding transaction volume", "Endogenous Market", "Funding", "Continuous", None, "injected"),
    ("Funding tail rate", "Endogenous Market", "Funding", "Continuous", None, "injected"),
    ("Funding tail premium", "Endogenous Market", "Funding", "Continuous", None, "injected"),
    ("Fed reverse-repo liquidity", "Endogenous Market", "Funding", "Continuous", None, "injected"),
    ("Dealer balance-sheet constraint", "Endogenous Market", "Funding", "Continuous", None, "injected"),
    ("Margin / haircut shock", "Endogenous Market", "Leverage", "Event/Continuous", None, "injected"),
    ("Leverage / deleveraging", "Endogenous Market", "Leverage", "Continuous/Event", None, "injected"),
    ("ETF flows", "Endogenous Market", "Flows", "Continuous", None, "injected"),
    ("Index / passive flows", "Endogenous Market", "Flows", "Continuous/Event", None, "injected"),
    ("Common institutional ownership", "Endogenous Market", "Ownership", "Slow-moving", None, "metadata"),
    ("Ownership concentration / fragility", "Endogenous Market", "Ownership", "Slow-moving", None, "metadata"),
    ("Crowded positioning", "Endogenous Market", "Positioning", "Continuous", None, "injected"),
    ("CTA / trend exposure", "Endogenous Market", "Positioning", "Continuous", None, "injected"),
    ("Risk-parity / vol-target exposure", "Endogenous Market", "Positioning", "Continuous", None, "injected"),
    ("Short interest", "Endogenous Market", "Positioning", "Continuous", None, "liquidity"),
    ("Borrow fee / securities lending", "Endogenous Market", "Positioning", "Continuous", None, "liquidity"),
    ("Dealer gamma", "Endogenous Market", "Derivatives", "Continuous", None, "injected"),
    ("Vanna / charm", "Endogenous Market", "Derivatives", "Continuous", None, "injected"),
    ("Options open interest / expiry", "Endogenous Market", "Derivatives", "Continuous/Event", None, "injected"),
    ("Implied correlation / dispersion", "Endogenous Market", "Derivatives", "Continuous", None, "injected"),
    ("Buyback / issuance / M&A flow", "Endogenous Market", "Corporate flows", "Event/Continuous", None, "event"),
    ("Index inclusion / rebalance", "Endogenous Market", "Indexing", "Event", None, "event"),
    ("Forced liquidation", "Endogenous Market", "Leverage", "Event", None, "event"),

    # Information / attention / jump propagation
    ("Economic policy uncertainty", "Information/Event", "Information", "Continuous", None, "injected"),
    ("Equity market uncertainty", "Information/Event", "Information", "Continuous", None, "injected"),
    ("News sentiment", "Information/Event", "Information", "Continuous", None, "injected"),
    ("News volume / attention", "Information/Event", "Information", "Continuous", None, "injected"),
    ("Search / social attention", "Information/Event", "Information", "Continuous", None, "injected"),
    ("Analyst attention", "Information/Event", "Information", "Continuous", None, "injected"),
    ("Legal / court event", "Information/Event", "Legal", "Event", None, "event"),
    ("Corporate action", "Information/Event", "Corporate event", "Event", None, "event"),
    ("Information diffusion / lead-lag", "Information/Event", "Information diffusion", "Derived", None, "derived"),
    ("Extreme moves / co-extremes (daily)", "Information/Event", "Extreme-move process", "Derived", None, "derived"),
    ("Intraday jumps / co-jumps", "Information/Event", "Jump process", "Intraday", None, "intraday"),

    # Structural / measurement / economic importance
    ("Currency translation", "Structural/Measurement", "Currency", "Transform", None, "metadata"),
    ("FX hedge overlay", "Structural/Measurement", "Currency", "Transform", None, "metadata"),
    ("Market-hours alignment", "Structural/Measurement", "Synchronization", "Transform", None, "metadata"),
    ("Trading calendar", "Structural/Measurement", "Synchronization", "Transform", None, "metadata"),
    ("Asset-type risk unit", "Structural/Measurement", "Risk space", "Transform", None, "metadata"),
    ("P&L risk-space / sensitivities", "Structural/Measurement", "Risk space", "Transform", None, "injected"),
    ("Market capitalization", "Structural/Measurement", "Economic importance", "Metadata", None, "metadata"),
    ("Index weight", "Structural/Measurement", "Economic importance", "Metadata", None, "metadata"),
    ("Portfolio weight", "Structural/Measurement", "Economic importance", "Metadata", None, "metadata"),
    ("DV01 / duration", "Structural/Measurement", "Risk sensitivity", "Metadata", None, "metadata"),
    ("CS01 / spread duration", "Structural/Measurement", "Risk sensitivity", "Metadata", None, "metadata"),
    ("Greeks / option sensitivities", "Structural/Measurement", "Risk sensitivity", "Metadata", None, "metadata"),
    ("Benchmark membership", "Structural/Measurement", "Market structure", "Metadata", None, "metadata"),

    # Asset-class-specific extensions
    ("Crypto market factor", "Endogenous Market", "Crypto", "Continuous", "BTC-USD", "proxy"),
    ("Crypto funding rate", "Endogenous Market", "Crypto", "Continuous", None, "injected"),
    ("Crypto basis", "Endogenous Market", "Crypto", "Continuous", None, "injected"),
    ("Stablecoin liquidity", "Endogenous Market", "Crypto", "Continuous", None, "injected"),
    ("Exchange inflow / outflow", "Endogenous Market", "Crypto", "Continuous", None, "injected"),
    ("Liquidation cascade", "Endogenous Market", "Crypto", "Event/Continuous", None, "event"),
    ("Token unlock / issuance", "Exogenous", "Crypto", "Event", None, "event"),
    ("Mortgage convexity hedging", "Endogenous Market", "Rates", "Continuous/Event", None, "injected"),
]


def force_registry() -> pd.DataFrame:
    return pd.DataFrame(
        _REGISTRY_ROWS,
        columns=["Force", "Mechanism", "Family", "Mode", "Default proxy", "Input channel"],
    )


DEFAULT_PROXY_METADATA = {
    "SPY": {"force": "Broad equity market", "mechanism": "Fundamental/Systematic", "family": "Market beta", "identification": "Proxy/associational"},
    "QQQ": {"force": "Growth / technology style", "mechanism": "Fundamental/Systematic", "family": "Style", "identification": "Proxy/associational"},
    "IWM": {"force": "Small-cap / size", "mechanism": "Fundamental/Systematic", "family": "Style", "identification": "Proxy/associational"},
    "SMH": {"force": "Semiconductor industry", "mechanism": "Fundamental/Systematic", "family": "Industry", "identification": "Proxy/associational"},
    "SOXX": {"force": "Semiconductor industry alt", "mechanism": "Fundamental/Systematic", "family": "Industry", "identification": "Proxy/associational"},
    "TLT": {"force": "Long-duration rates", "mechanism": "Exogenous", "family": "Rates", "identification": "Tradable proxy/associational"},
    "IEF": {"force": "Intermediate rates", "mechanism": "Exogenous", "family": "Rates", "identification": "Tradable proxy/associational"},
    "HYG": {"force": "High-yield credit", "mechanism": "Exogenous", "family": "Credit", "identification": "Tradable proxy/associational"},
    "LQD": {"force": "Investment-grade credit", "mechanism": "Exogenous", "family": "Credit", "identification": "Tradable proxy/associational"},
    "GLD": {"force": "Gold / safe haven", "mechanism": "Exogenous", "family": "Commodities", "identification": "Tradable proxy/associational"},
    "USO": {"force": "Oil / energy", "mechanism": "Exogenous", "family": "Commodities", "identification": "Tradable proxy/associational"},
    "UUP": {"force": "USD factor", "mechanism": "Exogenous", "family": "FX", "identification": "Tradable proxy/associational"},
    "^VIX": {"force": "Implied volatility / risk aversion", "mechanism": "Exogenous", "family": "Volatility", "identification": "Market-state proxy/associational"},
    "BTC-USD": {"force": "Crypto market factor", "mechanism": "Endogenous Market", "family": "Crypto", "identification": "Tradable proxy/associational"},
}
